name: Deploy Laravel NewPhanomAdmin

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH for deployment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Sync files to server
      run: |
        rsync -avzr --delete \
          -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/phanomprofes_usr/data/www/admin.phanomprofessionals.com/newphanomadmin/

    - name: Run Laravel deployment commands on server with explicit PHP 8.4 for Composer
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/phanomprofes_usr/data/www/admin.phanomprofessionals.com/newphanomadmin/
          PHP_BIN="/opt/php84/bin/php"
          COMPOSER_CMD="$PHP_BIN $(which composer 2>/dev/null || echo 'composer')"
          $COMPOSER_CMD install --no-interaction --prefer-dist --optimize-autoloader
          $PHP_BIN artisan migrate --force
          $PHP_BIN artisan config:cache
          $PHP_BIN artisan route:cache
          $PHP_BIN artisan view:cache
          $PHP_BIN artisan queue:restart || echo "Queue restart not needed or failed"
        EOF
